// Patch android/app/build.gradle (generated by expo prebuild) so release builds
// are signed with the upload keystore configured via MYAPP_UPLOAD_* properties
// in android/gradle.properties. Only run this when the keystore is present.
const fs = require("fs");
const path = require("path");

const gradlePath = path.join(__dirname, "..", "android", "app", "build.gradle");
let g = fs.readFileSync(gradlePath, "utf8");

if (g.includes("MYAPP_UPLOAD_STORE_FILE")) {
  console.log("signing already injected — skipping");
  process.exit(0);
}

// 1. Add a release entry inside the existing signingConfigs block.
const releaseConfig = `signingConfigs {
        release {
            if (!project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                throw new GradleException('MYAPP_UPLOAD_* signing properties are missing from android/gradle.properties')
            }
            storeFile file(MYAPP_UPLOAD_STORE_FILE)
            storePassword MYAPP_UPLOAD_STORE_PASSWORD
            keyAlias MYAPP_UPLOAD_KEY_ALIAS
            keyPassword MYAPP_UPLOAD_KEY_PASSWORD
        }`;
if (!g.includes("signingConfigs {")) {
  console.error("signingConfigs block not found in build.gradle");
  process.exit(1);
}
g = g.replace("signingConfigs {", releaseConfig);

// 2. Point the release buildType at it (expo template defaults it to the debug keystore).
const patched = g.replace(
  /(release\s*\{[^}]*?)signingConfig signingConfigs\.debug/s,
  "$1signingConfig signingConfigs.release",
);
if (patched === g) {
  console.error("release buildType signingConfig not found in build.gradle");
  process.exit(1);
}

fs.writeFileSync(gradlePath, patched);
console.log("release signing injected into build.gradle");
